/*class DatabaseAlreadyOpenException implements Exception {}
class UnableToGetDocumentsDirectory implements Exception {}
class DatabaseIsNotOpen implements Exception {}
class CouldNotDeleteUser implements Exception {}
class UserAlreadyExists implements Exception {}
class CoulNotFindUser implements Exception {}
class CouldNotDeleteNote implements Exception {}
class CoulNotFindNote implements Exception {}
class CoulNotUpdateNote implements Exception {}
class UserShouldBeSetBeforeReadingAllNotes implements Exception {}*/